### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [jcguu95/stumpwm-dynamic-float#2] opened 2022-09-26 20:59 UTC
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 344a632099d1ac4423a4a5d61a0a99b4189b175c

*stumpwm-dynamic-float* fails to build with the following error:

```
; caught WARNING:
;   Destructive function STABLE-SORT called on constant data: ((TINY T) 1 (MEDIUM M) 0 (LARGE L))
;   See also:
;     The ANSI Standard, Special Operator QUOTE
;     The ANSI Standard, Section 3.7.1
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1040760073}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm-dynamic-float" "src" "util">

```

[Full log here](http://report.quicklisp.org/2022-09-26/failure-report/stumpwm-dynamic-float.html)

**Comment by jcguu95** [comment] 2022-09-26 23:09
I cannot reproduce on `sbcl 2.2.7`, even with `(declaim (optimize (debug 3) (safety 3)))`. However, I understand that `stable-sort` is destructive, so applying that on a literal object is an [undefined behavior](http://clhs.lisp.se/Body/03_ga.htm). Would you mind if I just change

``` lisp
(stable-sort '((tiny t) 1 (medium m) 0 (large l))
             (sort-logic '(tiny medium large) :transformer #'car))
```

blindly to

``` lisp
(stable-sort (copy-list '((tiny t) 1 (medium m) 0 (large l)))
             (sort-logic '(tiny medium large) :transformer #'car))
```
?

**Comment by quicklisp** [comment] 2022-09-26 23:11
I don't think that would help. You are still calling sort on a literal
list.

**Comment by jcguu95** [comment] 2022-09-26 23:28
I wrote the parentheses wrong. Would you please check again?
```
(stable-sort (copy-list '((tiny t) 1 (medium m) 0 (large l)))
             (sort-logic '(tiny medium large) :transformer #'car))
```

**Comment by quicklisp** [comment] 2022-09-26 23:37
I think that would work.

**Comment by jcguu95** [comment] 2022-09-27 00:22
Should be fixed in this [commit](https://github.com/jcguu95/stumpwm-dynamic-float/commit/46e0ff354d9b0b450bb4ed6faa3c2c887505a638). Please let me know if it works. Thank you!

**Comment by quicklisp** [comment] 2022-10-11 08:45
Looks to me like it worked.

**Closed as completed** 2022-10-11 12:30 UTC
